openapi: "3.0.0"
info:
  title: "Endpoints"
  version: 1.0.0
servers:
  -
    url: "https://readme.lighting/api"
paths: {}
tags:
  - name: Messages
    description: Interact with the Vestaboard
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
