
Error validating the API definition! Run with -v to see the invalid definition.

OpenAPI schema validation failed.

REQUIRED must have required property 'required'

  34 |         "description": "This will send a message to the Vestaboard to be displayed",
  35 |         "parameters": [
> 36 |           {
     |           ^ ☹️  required is missing here!
  37 |             "in": "body",
  38 |             "name": "color",
  39 |             "schema": {

