# Check out our GitHub Action docs: https://docs.readme.com/docs/rdme

name: Sync OAS to ReadMe
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Generate OpenAPI file
        run: npm run oas
      - uses: readmeio/rdme@v8
        with:
          rdme: openapi openapi.json --key=${{ secrets.README_TOKEN }} --id=${{ secrets.API_DEFINITION_ID }}
